services:
  litrevu:
    container_name: litrevu
    # Docker stays up in background
    tty: true

    volumes:
      # Sharing project folder from Host to Docker
      - type: bind
        source: ./website
        target: /home/user/website

    # Share network Stack host to docker
    # Priviledge mode => Not safe for production
    #network_mode: host

    build:
      context: .
      dockerfile: Dockerfile
